import { GridBox, VerticalBox, Switch} from "std-widgets.slint";
    
export global Palette {
    out property <color> calc-background-color: root.race-mode ?  #050404: #271F30;
    out property <color> calc-text-color: root.race-mode ?  #F6F7EB:#ffffff ;
    out property <color> btn-border-color: root.race-mode ? transparent : transparent;
    out property <color> btn-background-color: root.race-mode ?  #003994:#6C5A49 ;
    out property <color> btn-text-color: root.race-mode ?  #F6F7EB:#ffffff ;
    out property <color> operator-btn-background-color: root.race-mode ?  #4C191B:#9BC59D ;
    out property <color> operator-btn-text-color: root.race-mode ?  #F6F7EB:#000000 ;
    out property <color> equal-btn-background-color: root.race-mode ?  #EE7674:#D0FCB3 ;
    out property <color> equal-btn-text-color: root.race-mode ? #000000 : #000000;
    in property <bool> race-mode: false;
}
export global Logic {
    callback btn-clicked(string);
}
         
export component Button {
    callback clicked;
    in property<string> btn_text;
    in property<string> btn_value : btn-text;
    in property <brush> background: Palette.btn-background-color;
    in property <brush> color: Palette.btn-text-color;
    Rectangle {
        min-width: 75px;
        min-height: 50px;
        background: area.pressed ? root.background.darker(60%) : area.has-hover ? root.background.darker(20%) : root.background;
        border-radius: 5px;
        border-width: 1px;
        border-color: Palette.btn-border-color;
        area := TouchArea {
            clicked => {
                Logic.btn-clicked(root.btn_value);
            }
        }
    }
    Text { 
        text: root.btn-text;
        color: root.color;
        font-size: 19px;
    }
}    
export component App inherits Window {
    in property <bool> race-mode: false;
    in property <string> value: "0";
    title: "UniUd E-Racing Team Calculator";
    icon: @image-url("media\\logo.png");
    min-width: 360px;
    min-height: 480px;
    background: Palette.calc-background-color;
    VerticalBox { 
        Text {
            font-size: 65px;
            text: value;
            overflow: clip;
            wrap: word-wrap;
            vertical-alignment: center;
            horizontal-alignment: right;
        }  
        GridBox {
            Switch {
                checked: false;
                toggled => {
                    Palette.race-mode = !Palette.race-mode;
                }
            }
            Row {
                Button { 
                    btn_text: "%";  
                }
                Button { 
                    btn_text: "Ans";
                    btn_value: "";
                }
                Button { 
                        btn_text: "C"; 
                }
                Button { 
                    btn_text: "<"; 
                    }
            }
            Row {
                Button { 
                    btn_text: "x³";
                    btn_value: "^3"; 
                }
                Button { 
                    btn_text: "x²";
                    btn_value: "^2"; 
                }
                Button { 
                    btn_text: "x10";
                    btn_value: "*10"; 
                }
                Button { 
                    btn_text: "/"; 
                    background: Palette.operator-btn-background-color; 
                    color: Palette.operator-btn-text-color; 
                }
                }
            Row {
                Button { 
                    btn_text: "7"; 
                }
                Button { 
                    btn_text: "8"; 
                }
                Button { 
                    btn_text: "9"; 
                }
                Button { 
                    btn_text: "x";
                    btn_value: "*"; 
                    background: Palette.operator-btn-background-color; 
                    color: Palette.operator-btn-text-color; 
                }
                }
            Row {
                Button { 
                    btn_text: "4"; 
                }
                Button { 
                    btn_text: "5"; 
                }
                Button { 
                    btn_text: "6"; 
                }
                Button { 
                    btn_text: "-"; 
                    background: Palette.operator-btn-background-color; 
                    color: Palette.operator-btn-text-color; 
                }
                }
            Row {
                Button { 
                    btn_text: "1"; 
                }
                Button { 
                    btn_text: "2"; 
                }
                Button { 
                    btn_text: "3"; 
                }
                Button { 
                    btn_text: "+"; 
                    background: Palette.operator-btn-background-color; 
                    color: Palette.operator-btn-text-color; 
                }
                }
            Row {
                Button { 
                    btn_text: "AC"; 
                }
                Button { 
                    btn_text: "0"; 
                }
                Button { 
                    btn_text: "."; 
                }
                Button { 
                    btn_text: "="; 
                    background: Palette.equal-btn-background-color; 
                    color: Palette.equal-btn-text-color; 
                }
            }
        }   
    }            
}